- name: "Add device '{{ secgws[item].name }}' to FAZ"
  fortinet.fortianalyzer.faz_dvm_cmd_add_device:
    access_token: "{{ ansible_httpapi_access_token }}"
    dvm_cmd_add_device:
      adom: "{{ adom_secgw }}"
      flags: [create_task, nonblocking]
      device:
        name: "{{ secgws[item].name }}"
        adm_usr: "{{ username }}"
        adm_pass: "{{ ansible_password }}"
        ip: "{{ secgws[item].mgmtip }}"
        mgmt_mode: 'faz' 
        sn: "{{ secgws[item].sn }}"
        os_type: 'fos'
        os_ver: '7.0'
        mr: 4
  register: faz_add_secgw_devices_installing_task

- name: Poll FAZ installing task
  ansible.builtin.include_tasks: "../common/tasks/_monitor_task_faz.yml"
  vars:
    fmgr_raw_task_result: "{{ faz_add_secgw_devices_installing_task }}"
