- name: Move unused interfaces
  fmgr_generic:
    access_token: '{{ fmg_access_token }}'
    method: set
    params:
      - url: "pm/config/device/{{ item.name }}/global/system/dns"
        data:
          domain: 'mno.com'
          primary: '8.8.8.8'
          protocol: 'cleartext'
          secondary: '8.8.4.4'
  loop:
    - '{{ secgws.seg1 }}'
    - '{{ secgws.seg2 }}'
  loop_control:
    label: "{{ item.name }}"
