- name: 'FMG Configure system global'
  fortinet.fortimanager.fmgr_system_global:
    access_token: "{{ access_token }}"
    system_global:
      adom_status: "{{ adom_status }}"
      hostname: "{{ hostname }}"
      timezone: "{{ fmc_timezone }}"

- name: 'FMG Allow FGT-VM'
  fortinet.fortimanager.fmgr_generic:
    access_token: "{{ access_token }}"
    method: set
    params:
      - url: '/cli/global/system/global'
        data:
          fgfm-allow-vm: 'enable'
          