[fortimanagers]
fortimanager01 ansible_host=10.254.1.60

[fortianalyzers]
fortianalyzer01 ansible_host=10.254.1.70

[gnbs]
gnb1 ansible_host=10.254.1.1 
gnb2 ansible_host=10.254.1.2

[fortimanagers:vars]
ansible_network_os=fortinet.fortimanager.fortimanager

[fortianalyzers:vars]
ansible_network_os=fortinet.fortianalyzer.fortianalyzer

[gnbs:vars]
ansible_user=root
ansible_ssh_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
