---
- name: Test Fortimanager connection
  hosts: fortimanagers
  gather_facts: false
  connection: httpapi
  collections:
    - fortinet.fortimanager
  tasks:
    - name: Get system status from FortiManager
      fortinet.fortimanager.fmgr_fact:
        access_token: "{{ ansible_httpapi_access_token }}"
        enable_log: true
        facts:
          selector: "sys_status"
      register: result
    - name: Display FortiManager system status
      debug:
        var: result
