- name: FGSP Static routes
  fmgr_generic:
    access_token: '{{ fmg_access_token }}'
    method: set
    params:
      - url: "pm/config/device/{{ item.name }}/vdom/root/router/static"
        data:
          - seq-num: 2
            device: '{{ item.static_routes[0].device }}'
            comment: '{{ item.static_routes[0].comment }}'
            bfd: 'enable'
            dst: '{{ item.static_routes[0].dst }}'
            gateway: '{{ item.static_routes[0].gateway }}'
          - seq-num: 3
            device: '{{ item.static_routes[1].device }}'
            comment: '{{ item.static_routes[1].comment }}'
            bfd: 'enable'
            dst: '{{ item.static_routes[1].dst }}'
            gateway: '{{ item.static_routes[1].gateway }}'
  loop:
    - '{{ secgws.seg1 }}'
    - '{{ secgws.seg2 }}'
  loop_control:
    label: "{{ item.name }}"