---
crl_scope_device_vdom:
  - name: "{{ ansible_facts.secgws.seg1.name }}"
    vdom: "{{ ansible_facts.secgws.region1_traffic_vdom }}"
  - name: "{{ ansible_facts.secgws.seg2.name }}"
    vdom: "{{ ansible_facts.secgws.region1_traffic_vdom }}"

