[fortimanagers]
fortimanager01 ansible_host=10.254.1.60

[fortianalyzers]
fortianalyzer01 ansible_host=10.254.1.70

[fortimanagers:vars]
ansible_network_os=fortinet.fortimanager.fortimanager

[fortianalyzers:vars]
ansible_network_os=fortinet.fortianalyzer.fortianalyzer

