---
policy_packages_scope_device_vdom:
  - name: "{{ secgws.seg1.name }}"
    vdom: "{{ secgws.region1_traffic_vdom }}"
  - name: "{{ secgws.seg2.name }}"
    vdom: "{{ secgws.region1_traffic_vdom }}"
