---
#- name: 9.1 Objects
#  ansible.builtin.include_tasks: '1_objects.yml'
#- name: 9.2 Objects6
#  ansible.builtin.include_tasks: '2_objects6.yml'
#- name: 9.3 User Peer
#  ansible.builtin.include_tasks: '3_user_peer.yml'
#- name: 9.4 IPsec
#  ansible.builtin.include_tasks: '4_ipsec.yml'
#- name: 9.5 Install devices
#  ansible.builtin.include_tasks: '../common/install_device.yml'
- name: vpntunnel test
  fortinet.fortimanager.fmgr_generic:
    access_token: "{{ access_token }}"
    method: get
    params:
      - url: "pm/config/adom/{{ adom_secgw }}/obj/dynamic/vpntunnel"
#         data:
#          -
#            name: "SecGW6"
#            authmethod: "signature"
#            certificate: '{{ item.certname }}'
#            ike-version: 2
#            interface: "{{ secgws.ipsec_loopback_interface_name }}"
#            ip-version: "6"
#            ipv6-end-ip: "fd00::30:cafe:ffff"
#            ipv6-prefix: 112
#            ipv6-split-include: "5G-Networks-ipv6"
#            ipv6-start-ip: "fd00::30:cafe:1"
#            local-gw6: "fd00::20:ff:1"
#            mode-cfg: "enable"
#            peertype: "peer"
#            peer: "mno_CA6"
#            dhgrp: "31"
#            proposal: "aes128gcm-prfsha256"
#            type: "dynamic"
#            fgsp-sync: "enable"
#            dpd: "on-idle"
#            dpd-retryinterval: 20
#
#  loop:
#    - '{{ secgws.seg1 }}'
#    - '{{ secgws.seg2 }}'
#  loop_control:
#    label: "{{ item.name }}"
