- name: 'Create dynamic interfaces'
  fortinet.fortimanager.fmgr_generic:
    access_token: "{{ ansible_facts.access_token }}"
    method: set
    params:
      - url: "/pm/config/adom/{{ adom_secgw }}/obj/dynamic/interface"
        data:
          - default-mapping: 'enable'
            defmap-intf: 'SecGW'
            description: 'IPsec Tunnel'
            name: 'SecGW'
            single-intf: 'enable'
          - default-mapping: 'enable'
            defmap-intf: "{{ secgws.ipsec_loopback_interface_name }}"
            description: 'IPsec Termination'
            name: "{{ secgws.ipsec_loopback_interface_name }}"
            single-intf: 'enable'
          - default-mapping: 'enable'
            defmap-intf: 'SZ_TRUST'
            description: 'RAN Trusted'
            name: 'SZ_TRUST'
            single-intf: 'enable'
          - default-mapping: 'enable'
            defmap-intf: 'SZ_UNTRUST'
            description: 'RAN Untrusted'
            name: 'SZ_UNTRUST'
            single-intf: 'enable'
  changed_when: false

- name: 'IPv6 Create dynamic interfaces'
  fortinet.fortimanager.fmgr_generic:
    access_token: "{{ ansible_facts.access_token }}"
    method: set
    params:
      - url: "/pm/config/adom/{{ adom_secgw }}/obj/dynamic/interface"
        data:
          - default-mapping: 'enable'
            defmap-intf: 'SecGW6'
            description: 'IPsec Tunnel'
            name: 'SecGW6'
            single-intf: 'enable'
  changed_when: false
  when: enable_ipv6 is true
