- name: "Create firewall policy package {{ secgws.policy_package }}"
  fortinet.fortimanager.fmgr_generic:
    access_token: "{{ ansible_httpapi_access_token }}"
    method: set
    params:
      - url: "/pm/pkg/adom/{{ adom_secgw }}"
        data:
          - name: "{{ secgws.policy_package }}"
            'package settings':
              central-nat: 'disable'
              consolidated-firewall-mode: 'disable'
              fwpolicy-implicit-log: 'disable'
              fwpolicy6-implicit-log: 'disable'
              ngfw-mode: 'profile-based'
            'scope member':
              - name: "{{ secgws.region1_group }}"
            type: 'pkg'
  changed_when: false
