- name: "FAZ Create ADOM {{ adom_secgw }}"
  fortinet.fortianalyzer.faz_dvmdb_adom:
    access_token: "{{ ansible_facts.access_token }}"
    state: present
    dvmdb_adom:
      name: "{{ adom_secgw }}"
