- name: 'Create system template'
  fortinet.fortimanager.fmgr_pm_devprof_adom:
    access_token: "{{ ansible_httpapi_access_token }}"
    adom: "{{ adom_secgw }}"
    pm_devprof_adom:
      name: "{{ secgws.system_template_name }}"
      description: 'System Template for SecGW'
      enabled_options: [dns, log, ntp, admin]
      type: 'devprof'
      scope_member:
        - name: "{{ secgws.seg1.name }}"
        - name: "{{ secgws.seg2.name }}"

- name: 'Set Template parameters'
  fortinet.fortimanager.fmgr_devprof_system_global:
    access_token: "{{ ansible_httpapi_access_token }}"
    adom: "{{ adom_secgw }}"
    devprof: "{{ secgws.system_template_name }}"
    devprof_system_global:
      #vdom_mode: 'multi-vdom' #not currently working in FMG module
      #lldp_reception: 'enable'
      #lldp_transmission: 'enable'
      #admin_sport: 443
      #timezone: "{{ secgws.timezone }}"
      admin_ssh_port: "{{ ssh_port }}"
      admintimeout: "{{ secgws.admintimeout }}"
      gui_ipv6: 'enable'
      gui_theme: 'graphite'

- name: 'Add DNS settings to system template'
  fortinet.fortimanager.fmgr_generic:
    access_token: "{{ ansible_httpapi_access_token }}"
    method: set
    params:
      - url: "pm/config/adom/{{ adom_secgw }}/devprof/{{ secgws.system_template_name }}/system/dns"
        data:
          primary: '10.254.1.254'
          secondary: '96.45.45.45'
          domain: 'mno.com'
          protocol: 'cleartext'

- name: 'Add NTP settings to system template'
  fortinet.fortimanager.fmgr_generic:
    access_token: "{{ ansible_httpapi_access_token }}"
    method: set
    params:
      - url: "pm/config/adom/{{ adom_secgw }}/devprof/{{ secgws.system_template_name }}/system/ntp"
        data:
          ntpsync: 1

- name: 'System Template FAZ'
  fortinet.fortimanager.fmgr_devprof_device_profile_fortianalyzer:
    access_token: "{{ ansible_httpapi_access_token }}"
    adom: "{{ adom_secgw }}"
    devprof: "{{ secgws.system_template_name }}"
    devprof_device_profile_fortianalyzer:
      target_sn: "{{ hostvars[groups['fortianalyzers'][0]]['faz_sn']  }}"
      target_ip: "{{ hostvars[groups['fortianalyzers'][0]]['ansible_host'] }}"
      target: 'others'

- name: 'System Template FAZ settings'
  fortinet.fortimanager.fmgr_devprof_log_fortianalyzer_setting:
    access_token: "{{ ansible_httpapi_access_token }}"
    adom: "{{ adom_secgw }}"
    devprof: "{{ secgws.system_template_name }}"
    devprof_log_fortianalyzer_setting:
      reliable: 'disable'
      upload_option: 'realtime'
      access_config: 'enable'
      