---
- name: IPsec phase1 reauth
  fortinet.fortimanager.fmgr_generic:
    access_token: "{{ ansible_httpapi_access_token }}"
    method: set
    params:
      - url: "pm/config/device/{{ item.name }}/vdom/{{ secgws.region1_traffic_vdom }}/vpn/ipsec/phase1-interface"
        data:
          -
            name: 'SecGW'
            reauth: 'enable'
            keylife: '240'
            digital-signature-auth: 'enable'
            signature-hash-alg:
              - 'sha2-384'
              - 'sha2-512'
  loop:
    - "{{ secgws.seg1 }}"
    - "{{ secgws.seg2 }}"
  loop_control:
    label: "{{ item.name }}"

- name: IPsec phase2
  fortinet.fortimanager.fmgr_generic:
    access_token: "{{ ansible_httpapi_access_token }}"
    method: set
    params:
      - url: "pm/config/device/{{ item.name }}/vdom/{{ secgws.region1_traffic_vdom }}/vpn/ipsec/phase2-interface"
        data:
          -
            name: 'SecGW'
            phase1name: 'SecGW'
            keylifeseconds: '120'
  loop:
    - "{{ secgws.seg1 }}"
    - "{{ secgws.seg2 }}"
  loop_control:
    label: "{{ item.name }}"
