- name: Zones
  fmgr_generic:
    access_token: '{{ fmg_access_token }}'
    method: set
    params:
      - url: "pm/config/device/{{ item.name }}/vdom/{{ secgws_region1_traffic_vdom }}/system/zone"
        data:
          -
            name: "SZ_RAN-UNTRUST"
            description: "RAN-UNTRUST Security Zone"
            interface:
              - "agg1.20"
              - "agg2.20"
            intrazone: "allow"
          -
            name: "SZ_RAN-TRUST"
            description: "RAN-TRUST Security Zone"
            interface:
              - "agg1.30"
              - "agg2.30"
            intrazone: "allow"
  loop:
    - '{{ secgws.seg1 }}'
    - '{{ secgws.seg2 }}'
  loop_control:
    label: "{{ item.name }}"
