- name: Dynamic Interfaces
  fmgr_generic:
    access_token: '{{ fmg_access_token }}'
    method: set
    params:
      - url: "pm/config/adom/{{ fmg_adom_secgw }}/obj/dynamic/interface"
        data:
          -
            default-mapping: "enable"
            defmap-intf: "SecGW"
            description: "IPSec Tunnel"
            name: "SecGW"
            single-intf: "enable"
          -
            default-mapping: "enable"
            defmap-intf: "IPSecGW6"
            description: "IPSec Tunnel"
            name: "IPSecGW6"
            single-intf: "enable"
          -
            default-mapping: "enable"
            defmap-intf: "Lo1-IPSecGW"
            description: "IPSec Termination"
            name: "Lo1-IPSecGW"
            single-intf: "enable"
          -
            default-mapping: "enable"
            defmap-intf: "SZ_TRUST"
            description: "RAN Trusted"
            name: "SZ_TRUST"
            single-intf: "enable"
          -
            default-mapping: "enable"
            defmap-intf: "SZ_UNTRUST"
            description: "RAN Untrusted"
            name: "SZ_UNTRUST"
            single-intf: "enable"
