
- name: Firewall DoS Policies IPv6
  fmgr_generic:
    access_token: '{{ fmg_access_token }}'
    method: set
    params:
      - url: "pm/config/adom/{{ fmg_adom_secgw }}/pkg/{{ secgw_policy_package }}/firewall/DoS-policy6"
        data:
          -
            anomaly:
              -
                action: "pass"
                log: "enable"
                name: "ip_src_session"
                status: "enable"
                threshold: "100"
              -
                action: "pass"
                log: "enable"
                name: "ip_dst_session"
                status: "enable"
                threshold: "50000"
              -
                action: "pass"
                log: "disable"
                name: "tcp_syn_flood"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "tcp_port_scan"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "tcp_src_session"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "tcp_dst_session"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "enable"
                name: "udp_flood"
                status: "enable"
                threshold: "10000"
              -
                action: "pass"
                log: "enable"
                name: "udp_scan"
                status: "enable"
                threshold: "200"
              -
                action: "pass"
                log: "enable"
                name: "udp_src_session"
                status: "enable"
                threshold: "100"
              -
                action: "pass"
                log: "enable"
                name: "udp_dst_session"
                status: "enable"
                threshold: "50000"
              -
                action: "pass"
                log: "enable"
                name: "icmp_flood"
                status: "enable"
                threshold: "250"
              -
                action: "pass"
                log: "enable"
                name: "icmp_sweep"
                status: "enable"
                threshold: "100"
              -
                action: "pass"
                log: "enable"
                name: "icmp_src_session"
                status: "enable"
                threshold: "300"
              -
                action: "pass"
                log: "enable"
                name: "icmp_dst_session"
                status: "enable"
                threshold: "10000"
              -
                action: "pass"
                log: "disable"
                name: "sctp_flood"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "sctp_scan"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "sctp_src_session"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "sctp_dst_session"
                status: "disable"
                threshold: "1000"
            dstaddr: "all"
            interface: "IPSecGW6"
            name: "Monitor RAN Untrust6"
            policyid: 600
            service: 
              - "ALL_ICMP"
              - "IKE"
              - "ESP"
            srcaddr: "all"
            status: "enable"
          -
            anomaly:
              -
                action: "block"
                log: "enable"
                name: "ip_src_session"
                status: "enable"
                threshold: "200"
              -
                action: "block"
                log: "enable"
                name: "ip_dst_session"
                status: "enable"
                threshold: "100000"
              -
                action: "block"
                log: "disable"
                name: "tcp_syn_flood"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "tcp_port_scan"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "tcp_src_session"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "tcp_dst_session"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "enable"
                name: "udp_flood"
                status: "enable"
                threshold: "100000"
              -
                action: "block"
                log: "enable"
                name: "udp_scan"
                status: "enable"
                threshold: "400"
              -
                action: "block"
                log: "enable"
                name: "udp_src_session"
                status: "enable"
                threshold: "4000"
              -
                action: "block"
                log: "enable"
                name: "udp_dst_session"
                status: "enable"
                threshold: "100000"
              -
                action: "block"
                log: "enable"
                name: "icmp_flood"
                status: "enable"
                threshold: "500"
              -
                action: "block"
                log: "enable"
                name: "icmp_sweep"
                status: "enable"
                threshold: "200"
              -
                action: "block"
                log: "enable"
                name: "icmp_src_session"
                status: "enable"
                threshold: "600"
              -
                action: "block"
                log: "enable"
                name: "icmp_dst_session"
                status: "enable"
                threshold: "10000"
              -
                action: "block"
                log: "disable"
                name: "sctp_flood"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "sctp_scan"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "sctp_src_session"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "sctp_dst_session"
                status: "disable"
                threshold: "1000"
            dstaddr: "all"
            interface: "IPSecGW6"
            name: "Block RAN Untrust6"
            policyid: 610
            service: 
              - "ALL_ICMP"
              - "IKE"
              - "ESP"
            srcaddr: "all"
            status: "enable"


- name: Firewall DoS Policies
  fmgr_generic:
    access_token: '{{ fmg_access_token }}'
    method: set
    params:
      - url: "pm/config/adom/{{ fmg_adom_secgw }}/pkg/{{ secgw_policy_package }}/firewall/DoS-policy"
        data:
          -
            anomaly:
              -
                action: "pass"
                log: "enable"
                name: "ip_src_session"
                status: "enable"
                threshold: "100"
              -
                action: "pass"
                log: "enable"
                name: "ip_dst_session"
                status: "enable"
                threshold: "50000"
              -
                action: "pass"
                log: "disable"
                name: "tcp_syn_flood"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "tcp_port_scan"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "tcp_src_session"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "tcp_dst_session"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "enable"
                name: "udp_flood"
                status: "enable"
                threshold: "10000"
              -
                action: "pass"
                log: "enable"
                name: "udp_scan"
                status: "enable"
                threshold: "200"
              -
                action: "pass"
                log: "enable"
                name: "udp_src_session"
                status: "enable"
                threshold: "100"
              -
                action: "pass"
                log: "enable"
                name: "udp_dst_session"
                status: "enable"
                threshold: "50000"
              -
                action: "pass"
                log: "enable"
                name: "icmp_flood"
                status: "enable"
                threshold: "250"
              -
                action: "pass"
                log: "enable"
                name: "icmp_sweep"
                status: "enable"
                threshold: "100"
              -
                action: "pass"
                log: "enable"
                name: "icmp_src_session"
                status: "enable"
                threshold: "300"
              -
                action: "pass"
                log: "enable"
                name: "icmp_dst_session"
                status: "enable"
                threshold: "10000"
              -
                action: "pass"
                log: "disable"
                name: "sctp_flood"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "sctp_scan"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "sctp_src_session"
                status: "disable"
                threshold: "1000"
              -
                action: "pass"
                log: "disable"
                name: "sctp_dst_session"
                status: "disable"
                threshold: "1000"
            dstaddr: "all"
            interface: "SecGW"
            name: "Monitor RAN Untrust"
            policyid: 400
            service: 
              - "ALL_ICMP"
              - "IKE"
              - "ESP"
            srcaddr: "all"
            status: "enable"
          -
            anomaly:
              -
                action: "block"
                log: "enable"
                name: "ip_src_session"
                status: "enable"
                threshold: "200"
              -
                action: "block"
                log: "enable"
                name: "ip_dst_session"
                status: "enable"
                threshold: "100000"
              -
                action: "block"
                log: "disable"
                name: "tcp_syn_flood"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "tcp_port_scan"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "tcp_src_session"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "tcp_dst_session"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "enable"
                name: "udp_flood"
                status: "enable"
                threshold: "100000"
              -
                action: "block"
                log: "enable"
                name: "udp_scan"
                status: "enable"
                threshold: "400"
              -
                action: "block"
                log: "enable"
                name: "udp_src_session"
                status: "enable"
                threshold: "4000"
              -
                action: "block"
                log: "enable"
                name: "udp_dst_session"
                status: "enable"
                threshold: "100000"
              -
                action: "block"
                log: "enable"
                name: "icmp_flood"
                status: "enable"
                threshold: "500"
              -
                action: "block"
                log: "enable"
                name: "icmp_sweep"
                status: "enable"
                threshold: "200"
              -
                action: "block"
                log: "enable"
                name: "icmp_src_session"
                status: "enable"
                threshold: "600"
              -
                action: "block"
                log: "enable"
                name: "icmp_dst_session"
                status: "enable"
                threshold: "10000"
              -
                action: "block"
                log: "disable"
                name: "sctp_flood"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "sctp_scan"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "sctp_src_session"
                status: "disable"
                threshold: "1000"
              -
                action: "block"
                log: "disable"
                name: "sctp_dst_session"
                status: "disable"
                threshold: "1000"
            dstaddr: "all"
            interface: "SecGW"
            name: "Block RAN Untrust"
            policyid: 410
            service: 
              - "ALL_ICMP"
              - "IKE"
              - "ESP"
            srcaddr: "all"
            status: "enable"
